spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atm?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: atm
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.MySQLDialect